=== waldirjunior/siteMouseBox/entretenimento/imdb/testes/api/movie/method.dtd
<!ELEMENT method (param*,errors,example,information)>
<!ATTLIST method
        type (GET | POST | PUT | DELETE | HEAD | CONNECT | OPTIONS | TRACE | PATCH) #REQUIRED
        uri CDATA #REQUIRED
        description CDATA #REQUIRED
        deprecated (Y | N ) #IMPLIED
        hidden (Y | N ) #IMPLIED>
<!ELEMENT param (option*)>
<!ATTLIST param
        name CDATA #REQUIRED
        type (string | boolean| integer | float | double | enumerated | array | file ) #REQUIRED
        required (Y | N ) #IMPLIED
        description CDATA #REQUIRED
        value CDATA #IMPLIED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
        value CDATA #REQUIRED
        description CDATA #REQUIRED>
<!ELEMENT errors (error)*>
<!ELEMENT error (#PCDATA)>
<!ATTLIST error
        code CDATA #REQUIRED>
<!ELEMENT example (#PCDATA)>
<!ELEMENT information (#PCDATA)>

=== waldirjunior/siteMouseBox/entretenimento/imdb/testes/api/search/search.xml
<!DOCTYPE method SYSTEM "method.dtd">
<method type="GET" uri="/" description="Search over all database available information.">

	<param name="s" type="string" required="N" value="Batman" description="A valid IMDb ID (e.g. tt1285016)." />
	<param name="page" type="integer" required="N" value="2" description="Page number" />

	<errors>
		<error code="100" />
		<error code="101" />
	</errors>
	
	<example><![CDATA[]]></example>
	<information><![CDATA[]]></information>

</method>
